### ISSUE TITLE
Zero index 

### ISSUE THREAD

**Issue by reginaastri** [WilCrofter/GenS.jl#3]
I'm calling genS with incorrect parameters but at the entry for (5,6), that is xmitr 5 and rcvr 6, a zero for the row index appears. The following code calls probePos and genS (with incorrect parameters) and prints the xmitr,rcvr pairs followed by a list of values which are linear combinations of the i,j  indices associated with the pairs. For (xmitr,rcvr)==(5,6) the first entry is 0. 

using GenS

function zeroRow()
    r2 = Float64[-.1 8.1;   -.1 -0.1;     8.1 -0.1;    8.1 8.1]
    grid = .5
    width = 8
    height = 8
    xmitr,rcvr = probePos(8,r2)
    data = genS(width,height,grid,xmitr,rcvr)
    for (j in 1:height)
      for (i in 1:width)
	  col = (data[i,j][1][:,1]-1)*width + data[i,j][1][:,2]	
	  println(i,"  ",j," * ",col)
      end #i
    end #j
end #function

**Comment by WilCrofter** [comment]
[Fixed and test added.](https://github.com/WilCrofter/GenS.jl/commit/b1f43db03cf40e2c82896f5821d9105d4f9f2106)
